import type { FormField } from "@/components/forms/types";

const uid = (prefix: string, i: number) => `${prefix}-${i}`;

export const dentistryTemplates: { area: string; module_type: string; form_type: string; title: string; description: string; content_json: FormField[] }[] = [
  // ── Anamnese Odontológica ──
  {
    area: "dentistry", module_type: "anamnese_odontologica", form_type: "standard",
    title: "Ficha de Anamnese Odontológica",
    description: "Avaliação inicial do paciente odontológico",
    content_json: [
      { id: uid("do",0), label: "Identificação", type: "section_header" },
      { id: uid("do",1), label: "Nome completo", type: "text", required: true },
      { id: uid("do",2), label: "Idade", type: "text", required: true },
      { id: uid("do",3), label: "Queixa principal", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("do",4), label: "História da Doença Atual", type: "section_header" },
      { id: uid("do",5), label: "Descrição detalhada da queixa (início, evolução, fatores)", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("do",6), label: "Antecedentes", type: "section_header" },
      { id: uid("do",7), label: "Antecedentes médicos e odontológicos", type: "textarea", required: true, max_score: 1 },
      { id: uid("do",8), label: "Medicamentos em uso", type: "textarea", max_score: 0.5 },
      { id: uid("do",9), label: "Alergias", type: "textarea", max_score: 0.5 },
      { id: uid("do",10), label: "Hábitos parafuncionais (bruxismo, onicofagia, etc.)", type: "checkbox", options: ["Bruxismo","Onicofagia","Mordedura labial/bochecha","Respiração bucal","Sucção digital","Nenhum"], max_score: 1 },
      { id: uid("do",11), label: "Hábitos de Higiene", type: "section_header" },
      { id: uid("do",12), label: "Frequência de escovação", type: "radio", options: ["1x/dia","2x/dia","3x/dia","+3x/dia"], max_score: 0.5 },
      { id: uid("do",13), label: "Uso de fio dental", type: "radio", options: ["Sim, diariamente","Às vezes","Não utiliza"], max_score: 0.5 },
      { id: uid("do",14), label: "Uso de enxaguatório", type: "radio", options: ["Sim","Não"], max_score: 0.5 },
      { id: uid("do",15), label: "Última visita ao dentista", type: "text", max_score: 0.5 },
      { id: uid("do",16), label: "Observações adicionais", type: "textarea", max_score: 0.5 },
    ],
  },
  {
    area: "dentistry", module_type: "anamnese_odontologica", form_type: "answer_key",
    title: "Espelho — Anamnese Odontológica",
    description: "Gabarito de anamnese odontológica",
    content_json: [
      { id: uid("doe",0), label: "Identificação", type: "section_header" },
      { id: uid("doe",3), label: "Queixa principal", type: "textarea", max_score: 1.5, correct_answer: "Registrar nas palavras do paciente com detalhes de localização e duração." },
      { id: uid("doe",4), label: "HDA", type: "section_header" },
      { id: uid("doe",5), label: "Descrição da queixa", type: "textarea", max_score: 1.5, correct_answer: "Início, duração, fatores de melhora/piora, tratamentos prévios." },
      { id: uid("doe",6), label: "Antecedentes", type: "section_header" },
      { id: uid("doe",7), label: "Antecedentes", type: "textarea", max_score: 1, correct_answer: "Doenças sistêmicas, cirurgias, tratamentos odontológicos anteriores." },
      { id: uid("doe",10), label: "Hábitos parafuncionais", type: "checkbox", options: ["Bruxismo","Onicofagia","Mordedura labial/bochecha","Respiração bucal","Sucção digital","Nenhum"], max_score: 1 },
    ],
  },
  // ── Exame Clínico ──
  {
    area: "dentistry", module_type: "exame_clinico", form_type: "standard",
    title: "Ficha de Exame Clínico Odontológico",
    description: "Exame extraoral, intraoral e periodontal",
    content_json: [
      { id: uid("ec",0), label: "Exame Extraoral", type: "section_header" },
      { id: uid("ec",1), label: "Face (simetria, linfonodos, ATM)", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("ec",2), label: "Exame Intraoral", type: "section_header" },
      { id: uid("ec",3), label: "Mucosa (lábios, bochechas, palato, língua, assoalho)", type: "textarea", required: true, max_score: 2 },
      { id: uid("ec",4), label: "Condição gengival", type: "textarea", required: true, max_score: 1 },
      { id: uid("ec",5), label: "Odontograma (dentes presentes, ausentes, restaurados, cariados)", type: "textarea", required: true, max_score: 2 },
      { id: uid("ec",6), label: "Avaliação Periodontal", type: "section_header" },
      { id: uid("ec",7), label: "PSR (Periodontal Screening and Recording)", type: "textarea", max_score: 1.5 },
      { id: uid("ec",8), label: "Índice de placa visível (%)", type: "text", max_score: 1 },
      { id: uid("ec",9), label: "Sangramento à sondagem", type: "radio", options: ["Sim","Não"], max_score: 0.5 },
      { id: uid("ec",10), label: "Observações do exame", type: "textarea", max_score: 0.5 },
    ],
  },
  {
    area: "dentistry", module_type: "exame_clinico", form_type: "answer_key",
    title: "Espelho — Exame Clínico",
    description: "Gabarito de exame clínico odontológico",
    content_json: [
      { id: uid("ece",0), label: "Exame Extraoral", type: "section_header" },
      { id: uid("ece",1), label: "Face", type: "textarea", max_score: 1.5, correct_answer: "Avaliar simetria facial, palpação de linfonodos e ATM (abertura, desvio, estalido)." },
      { id: uid("ece",2), label: "Exame Intraoral", type: "section_header" },
      { id: uid("ece",3), label: "Mucosa", type: "textarea", max_score: 2, correct_answer: "Exame sistemático de todos os tecidos moles: lábios, mucosa jugal, palato duro e mole, língua (dorso, ventre, bordas), assoalho." },
      { id: uid("ece",5), label: "Odontograma", type: "textarea", max_score: 2, correct_answer: "Registro completo com notação FDI de todos os dentes e suas condições." },
      { id: uid("ece",6), label: "Periodontal", type: "section_header" },
      { id: uid("ece",7), label: "PSR", type: "textarea", max_score: 1.5, correct_answer: "Sondagem em 6 sítios por sextante, registro do maior código por sextante." },
    ],
  },
  // ── Plano de Tratamento ──
  {
    area: "dentistry", module_type: "plano_tratamento", form_type: "standard",
    title: "Plano de Tratamento Odontológico",
    description: "Planejamento integrado do tratamento",
    content_json: [
      { id: uid("pt",0), label: "Diagnósticos", type: "section_header" },
      { id: uid("pt",1), label: "Diagnósticos identificados", type: "textarea", required: true, max_score: 2 },
      { id: uid("pt",2), label: "Priorização", type: "section_header" },
      { id: uid("pt",3), label: "Fase 1 — Urgência (se aplicável)", type: "textarea", max_score: 1 },
      { id: uid("pt",4), label: "Fase 2 — Adequação do meio bucal", type: "textarea", required: true, max_score: 2 },
      { id: uid("pt",5), label: "Fase 3 — Reabilitação", type: "textarea", max_score: 1.5 },
      { id: uid("pt",6), label: "Fase 4 — Manutenção", type: "textarea", max_score: 1 },
      { id: uid("pt",7), label: "Prognóstico", type: "section_header" },
      { id: uid("pt",8), label: "Prognóstico geral", type: "radio", options: ["Bom","Regular","Reservado","Ruim"], required: true, max_score: 1 },
      { id: uid("pt",9), label: "Justificativa do prognóstico", type: "textarea", max_score: 1.5 },
    ],
  },
  {
    area: "dentistry", module_type: "plano_tratamento", form_type: "answer_key",
    title: "Espelho — Plano de Tratamento",
    description: "Gabarito de plano de tratamento",
    content_json: [
      { id: uid("pte",0), label: "Diagnósticos", type: "section_header" },
      { id: uid("pte",1), label: "Diagnósticos", type: "textarea", max_score: 2, correct_answer: "Diagnóstico de cárie, periodontal, endodôntico e protético com CID-10 quando aplicável." },
      { id: uid("pte",2), label: "Priorização", type: "section_header" },
      { id: uid("pte",4), label: "Adequação do meio bucal", type: "textarea", max_score: 2, correct_answer: "Profilaxia, raspagem, restaurações provisórias, controle de placa, orientação de higiene." },
      { id: uid("pte",8), label: "Prognóstico", type: "radio", options: ["Bom","Regular","Reservado","Ruim"], max_score: 1 },
      { id: uid("pte",9), label: "Justificativa", type: "textarea", max_score: 1.5, correct_answer: "Basear em fatores de risco, cooperação do paciente e complexidade do caso." },
    ],
  },
  // ── Orientação de Higiene ──
  {
    area: "dentistry", module_type: "orientacao_higiene", form_type: "standard",
    title: "Ficha de Orientação de Higiene Bucal",
    description: "Educação em saúde bucal",
    content_json: [
      { id: uid("oh",0), label: "Técnica de Escovação", type: "section_header" },
      { id: uid("oh",1), label: "Técnica recomendada e orientações", type: "textarea", required: true, max_score: 2 },
      { id: uid("oh",2), label: "Tipo de escova recomendada", type: "radio", options: ["Macia","Extra-macia","Elétrica"], max_score: 0.5 },
      { id: uid("oh",3), label: "Uso do Fio Dental", type: "section_header" },
      { id: uid("oh",4), label: "Orientações sobre fio dental / escova interdental", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("oh",5), label: "Enxaguatório Bucal", type: "section_header" },
      { id: uid("oh",6), label: "Indicação e tipo de enxaguatório", type: "textarea", max_score: 1 },
      { id: uid("oh",7), label: "Orientações por Condição", type: "section_header" },
      { id: uid("oh",8), label: "Orientações específicas para a condição do paciente", type: "textarea", required: true, max_score: 2.5 },
      { id: uid("oh",9), label: "Frequência de retorno recomendada", type: "text", max_score: 0.5 },
      { id: uid("oh",10), label: "Materiais educativos fornecidos", type: "textarea", max_score: 0.5 },
    ],
  },
  {
    area: "dentistry", module_type: "orientacao_higiene", form_type: "answer_key",
    title: "Espelho — Orientação de Higiene",
    description: "Gabarito de orientação de higiene bucal",
    content_json: [
      { id: uid("ohe",0), label: "Escovação", type: "section_header" },
      { id: uid("ohe",1), label: "Técnica recomendada", type: "textarea", max_score: 2, correct_answer: "Técnica de Bass modificada: angulação 45°, movimentos vibratórios suaves, incluir língua." },
      { id: uid("ohe",3), label: "Fio Dental", type: "section_header" },
      { id: uid("ohe",4), label: "Orientações", type: "textarea", max_score: 1.5, correct_answer: "Demonstrar técnica correta, indicar interdental quando espaços permitirem." },
      { id: uid("ohe",7), label: "Por Condição", type: "section_header" },
      { id: uid("ohe",8), label: "Orientações específicas", type: "textarea", max_score: 2.5, correct_answer: "Adaptar orientações à condição: gengivite (controle de placa), ortodontia (escova interdental), prótese (higienização específica)." },
    ],
  },
];
