import type { FormField } from "@/components/forms/types";

const uid = (prefix: string, i: number) => `${prefix}-${i}`;

export const nursingTemplates: { area: string; module_type: string; form_type: string; title: string; description: string; content_json: FormField[] }[] = [
  // ── Acolhimento ──
  {
    area: "nursing", module_type: "acolhimento", form_type: "standard",
    title: "Ficha de Acolhimento com Classificação de Risco",
    description: "Protocolo Manchester adaptado para simulação",
    content_json: [
      { id: uid("ac",0), label: "Identificação do Paciente", type: "section_header" },
      { id: uid("ac",1), label: "Nome completo", type: "text", required: true },
      { id: uid("ac",2), label: "Data de nascimento", type: "date", required: true },
      { id: uid("ac",3), label: "Sexo", type: "radio", options: ["Masculino","Feminino","Outro"], required: true },
      { id: uid("ac",4), label: "Queixa Principal", type: "section_header" },
      { id: uid("ac",5), label: "Motivo da procura ao serviço", type: "textarea", required: true, max_score: 1 },
      { id: uid("ac",6), label: "Início dos sintomas", type: "text", max_score: 0.5 },
      { id: uid("ac",7), label: "Sinais Vitais", type: "section_header" },
      { id: uid("ac",8), label: "PA (mmHg)", type: "text", required: true, max_score: 0.5 },
      { id: uid("ac",9), label: "FC (bpm)", type: "text", required: true, max_score: 0.5 },
      { id: uid("ac",10), label: "FR (irpm)", type: "text", required: true, max_score: 0.5 },
      { id: uid("ac",11), label: "Temperatura (°C)", type: "text", required: true, max_score: 0.5 },
      { id: uid("ac",12), label: "SpO₂ (%)", type: "text", required: true, max_score: 0.5 },
      { id: uid("ac",13), label: "Escala de dor (0-10)", type: "scale", scale_max: 10, max_score: 0.5 },
      { id: uid("ac",14), label: "Classificação de Risco", type: "section_header" },
      { id: uid("ac",15), label: "Classificação Manchester", type: "radio", options: ["Vermelho — Emergência","Laranja — Muito urgente","Amarelo — Urgente","Verde — Pouco urgente","Azul — Não urgente"], required: true, max_score: 2, option_scores: {"0":2,"1":2,"2":2,"3":2,"4":2} },
      { id: uid("ac",16), label: "Justificativa da classificação", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("ac",17), label: "Alergias conhecidas", type: "textarea", max_score: 0.5 },
      { id: uid("ac",18), label: "Medicamentos em uso", type: "textarea", max_score: 0.5 },
      { id: uid("ac",19), label: "Observações da enfermagem", type: "textarea", max_score: 0.5 },
    ],
  },
  {
    area: "nursing", module_type: "acolhimento", form_type: "answer_key",
    title: "Espelho — Acolhimento",
    description: "Gabarito com critérios Manchester",
    content_json: [
      { id: uid("ace",0), label: "Identificação do Paciente", type: "section_header" },
      { id: uid("ace",1), label: "Nome completo", type: "text" },
      { id: uid("ace",2), label: "Data de nascimento", type: "date" },
      { id: uid("ace",3), label: "Sexo", type: "radio", options: ["Masculino","Feminino","Outro"] },
      { id: uid("ace",4), label: "Queixa Principal", type: "section_header" },
      { id: uid("ace",5), label: "Motivo da procura ao serviço", type: "textarea", max_score: 1, correct_answer: "Descrever motivo objetivo da busca ao serviço de saúde." },
      { id: uid("ace",6), label: "Início dos sintomas", type: "text", max_score: 0.5, correct_answer: "Registrar tempo de início (horas, dias)." },
      { id: uid("ace",7), label: "Sinais Vitais", type: "section_header" },
      { id: uid("ace",8), label: "PA (mmHg)", type: "text", max_score: 0.5, correct_answer: "Aferição correta com técnica adequada." },
      { id: uid("ace",9), label: "FC (bpm)", type: "text", max_score: 0.5, correct_answer: "Pulso radial por 1 minuto." },
      { id: uid("ace",10), label: "FR (irpm)", type: "text", max_score: 0.5, correct_answer: "Contagem discreta por 1 minuto." },
      { id: uid("ace",11), label: "Temperatura (°C)", type: "text", max_score: 0.5, correct_answer: "Axilar, oral ou timpânica." },
      { id: uid("ace",12), label: "SpO₂ (%)", type: "text", max_score: 0.5, correct_answer: "Oximetria de pulso com posicionamento correto." },
      { id: uid("ace",13), label: "Escala de dor (0-10)", type: "scale", scale_max: 10, max_score: 0.5 },
      { id: uid("ace",14), label: "Classificação de Risco", type: "section_header" },
      { id: uid("ace",15), label: "Classificação Manchester", type: "radio", options: ["Vermelho — Emergência","Laranja — Muito urgente","Amarelo — Urgente","Verde — Pouco urgente","Azul — Não urgente"], max_score: 2 },
      { id: uid("ace",16), label: "Justificativa da classificação", type: "textarea", max_score: 1.5, correct_answer: "Justificar com base nos discriminadores do Protocolo Manchester." },
      { id: uid("ace",17), label: "Alergias conhecidas", type: "textarea", max_score: 0.5, correct_answer: "Registrar alergias e tipo de reação." },
      { id: uid("ace",18), label: "Medicamentos em uso", type: "textarea", max_score: 0.5, correct_answer: "Nome, dose, frequência." },
      { id: uid("ace",19), label: "Observações da enfermagem", type: "textarea", max_score: 0.5, correct_answer: "Aspectos relevantes observados no acolhimento." },
    ],
  },
  // ── SAE ──
  {
    area: "nursing", module_type: "sae", form_type: "standard",
    title: "Histórico de Enfermagem — NANDA/NIC/NOC",
    description: "Sistematização da Assistência de Enfermagem completa",
    content_json: [
      { id: uid("sae",0), label: "1. Histórico de Enfermagem", type: "section_header" },
      { id: uid("sae",1), label: "Anamnese (entrevista com paciente/família)", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("sae",2), label: "Exame físico cefalocaudal", type: "textarea", required: true, max_score: 2 },
      { id: uid("sae",3), label: "2. Diagnósticos de Enfermagem (NANDA)", type: "section_header" },
      { id: uid("sae",4), label: "Diagnóstico 1 (título + fatores relacionados + características definidoras)", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("sae",5), label: "Diagnóstico 2", type: "textarea", max_score: 1 },
      { id: uid("sae",6), label: "Diagnóstico 3", type: "textarea", max_score: 0.5 },
      { id: uid("sae",7), label: "3. Resultados Esperados (NOC)", type: "section_header" },
      { id: uid("sae",8), label: "Resultados esperados para cada diagnóstico", type: "textarea", required: true, max_score: 1 },
      { id: uid("sae",9), label: "4. Intervenções de Enfermagem (NIC)", type: "section_header" },
      { id: uid("sae",10), label: "Prescrição de enfermagem com intervenções e atividades", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("sae",11), label: "5. Avaliação", type: "section_header" },
      { id: uid("sae",12), label: "Avaliação dos resultados alcançados", type: "textarea", required: true, max_score: 1 },
    ],
  },
  {
    area: "nursing", module_type: "sae", form_type: "answer_key",
    title: "Espelho — SAE NANDA/NIC/NOC",
    description: "Gabarito SAE com taxonomias",
    content_json: [
      { id: uid("saee",0), label: "1. Histórico de Enfermagem", type: "section_header" },
      { id: uid("saee",1), label: "Anamnese", type: "textarea", max_score: 1.5, correct_answer: "Dados completos: queixa, história, antecedentes, hábitos, medicamentos." },
      { id: uid("saee",2), label: "Exame físico cefalocaudal", type: "textarea", max_score: 2, correct_answer: "Avaliar sistematicamente: cabeça, pescoço, tórax, abdome, MMSS, MMII, pele." },
      { id: uid("saee",3), label: "2. Diagnósticos de Enfermagem (NANDA)", type: "section_header" },
      { id: uid("saee",4), label: "Diagnóstico 1", type: "textarea", max_score: 1.5, correct_answer: "Formato: Título NANDA + Fatores relacionados + Características definidoras." },
      { id: uid("saee",5), label: "Diagnóstico 2", type: "textarea", max_score: 1, correct_answer: "Segundo diagnóstico prioritário com taxonomia NANDA correta." },
      { id: uid("saee",6), label: "Diagnóstico 3", type: "textarea", max_score: 0.5, correct_answer: "Diagnóstico adicional relevante." },
      { id: uid("saee",7), label: "3. Resultados Esperados (NOC)", type: "section_header" },
      { id: uid("saee",8), label: "Resultados esperados", type: "textarea", max_score: 1, correct_answer: "Vincular resultado NOC a cada diagnóstico com indicadores mensuráveis." },
      { id: uid("saee",9), label: "4. Intervenções de Enfermagem (NIC)", type: "section_header" },
      { id: uid("saee",10), label: "Prescrição de enfermagem", type: "textarea", max_score: 1.5, correct_answer: "Intervenções NIC com atividades específicas, frequência e responsável." },
      { id: uid("saee",11), label: "5. Avaliação", type: "section_header" },
      { id: uid("saee",12), label: "Avaliação dos resultados", type: "textarea", max_score: 1, correct_answer: "Comparar resultados obtidos com os esperados e replanejar se necessário." },
    ],
  },
  // ── Evolução ──
  {
    area: "nursing", module_type: "evolucao", form_type: "standard",
    title: "Evolução de Enfermagem",
    description: "Registro SOAP adaptado para enfermagem",
    content_json: [
      { id: uid("ev",0), label: "S — Subjetivo", type: "section_header" },
      { id: uid("ev",1), label: "Relato do paciente/família", type: "textarea", required: true, max_score: 2 },
      { id: uid("ev",2), label: "O — Objetivo", type: "section_header" },
      { id: uid("ev",3), label: "Dados objetivos (exame físico, sinais vitais, exames)", type: "textarea", required: true, max_score: 2 },
      { id: uid("ev",4), label: "A — Avaliação", type: "section_header" },
      { id: uid("ev",5), label: "Avaliação dos diagnósticos de enfermagem vigentes", type: "textarea", required: true, max_score: 3 },
      { id: uid("ev",6), label: "P — Plano", type: "section_header" },
      { id: uid("ev",7), label: "Plano de cuidados atualizado", type: "textarea", required: true, max_score: 3 },
    ],
  },
  {
    area: "nursing", module_type: "evolucao", form_type: "answer_key",
    title: "Espelho — Evolução de Enfermagem",
    description: "Gabarito de evolução",
    content_json: [
      { id: uid("eve",0), label: "S — Subjetivo", type: "section_header" },
      { id: uid("eve",1), label: "Relato do paciente/família", type: "textarea", max_score: 2, correct_answer: "Queixas, relato de melhora/piora, adesão às orientações." },
      { id: uid("eve",2), label: "O — Objetivo", type: "section_header" },
      { id: uid("eve",3), label: "Dados objetivos", type: "textarea", max_score: 2, correct_answer: "Sinais vitais, estado geral, achados do exame físico direcionado." },
      { id: uid("eve",4), label: "A — Avaliação", type: "section_header" },
      { id: uid("eve",5), label: "Avaliação dos diagnósticos", type: "textarea", max_score: 3, correct_answer: "Avaliar cada diagnóstico NANDA: resolvido, mantido ou novo. Justificar." },
      { id: uid("eve",6), label: "P — Plano", type: "section_header" },
      { id: uid("eve",7), label: "Plano de cuidados atualizado", type: "textarea", max_score: 3, correct_answer: "Manter, ajustar ou suspender intervenções. Incluir novas ações se necessário." },
    ],
  },
  // ── Passagem de Plantão ──
  {
    area: "nursing", module_type: "passagem_plantao", form_type: "standard",
    title: "Ficha SBAR — Passagem de Plantão",
    description: "Comunicação estruturada entre equipes",
    content_json: [
      { id: uid("sb",0), label: "S — Situação", type: "section_header" },
      { id: uid("sb",1), label: "Identificação do paciente e motivo da comunicação", type: "textarea", required: true, max_score: 2 },
      { id: uid("sb",2), label: "B — Background (Contexto)", type: "section_header" },
      { id: uid("sb",3), label: "Antecedentes relevantes, diagnósticos e tratamentos", type: "textarea", required: true, max_score: 3 },
      { id: uid("sb",4), label: "A — Avaliação", type: "section_header" },
      { id: uid("sb",5), label: "Avaliação atual do paciente (sinais vitais, estado clínico)", type: "textarea", required: true, max_score: 2.5 },
      { id: uid("sb",6), label: "R — Recomendação", type: "section_header" },
      { id: uid("sb",7), label: "Recomendações para o próximo plantão", type: "textarea", required: true, max_score: 2.5 },
    ],
  },
  {
    area: "nursing", module_type: "passagem_plantao", form_type: "answer_key",
    title: "Espelho — SBAR",
    description: "Gabarito de passagem de plantão",
    content_json: [
      { id: uid("sbe",0), label: "S — Situação", type: "section_header" },
      { id: uid("sbe",1), label: "Identificação e motivo", type: "textarea", max_score: 2, correct_answer: "Nome, leito, diagnóstico principal e motivo da passagem." },
      { id: uid("sbe",2), label: "B — Background", type: "section_header" },
      { id: uid("sbe",3), label: "Antecedentes e tratamentos", type: "textarea", max_score: 3, correct_answer: "Histórico relevante, medicamentos, procedimentos realizados, alergias." },
      { id: uid("sbe",4), label: "A — Avaliação", type: "section_header" },
      { id: uid("sbe",5), label: "Avaliação atual", type: "textarea", max_score: 2.5, correct_answer: "Estado geral, sinais vitais recentes, nível de consciência, intercorrências." },
      { id: uid("sbe",6), label: "R — Recomendação", type: "section_header" },
      { id: uid("sbe",7), label: "Recomendações", type: "textarea", max_score: 2.5, correct_answer: "Pendências, exames aguardando, cuidados prioritários, sinais de alerta." },
    ],
  },
];
