import type { FormField } from "@/components/forms/types";

const uid = (prefix: string, i: number) => `${prefix}-${i}`;

export const nutritionTemplates: { area: string; module_type: string; form_type: string; title: string; description: string; content_json: FormField[] }[] = [
  // ── Anamnese Nutricional ──
  {
    area: "nutrition", module_type: "anamnese_nutricional", form_type: "standard",
    title: "Ficha de Anamnese Nutricional",
    description: "Avaliação nutricional completa do paciente",
    content_json: [
      { id: uid("nn",0), label: "Dados Pessoais", type: "section_header" },
      { id: uid("nn",1), label: "Nome completo", type: "text", required: true },
      { id: uid("nn",2), label: "Idade / Data de nascimento", type: "text", required: true },
      { id: uid("nn",3), label: "Sexo", type: "radio", options: ["Masculino","Feminino","Outro"] },
      { id: uid("nn",4), label: "Ocupação", type: "text" },
      { id: uid("nn",5), label: "História Alimentar", type: "section_header" },
      { id: uid("nn",6), label: "Recordatório alimentar de 24h", type: "textarea", required: true, max_score: 2 },
      { id: uid("nn",7), label: "Frequência alimentar (grupos alimentares)", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("nn",8), label: "Restrições alimentares / Alergias", type: "textarea", max_score: 0.5 },
      { id: uid("nn",9), label: "Preferências e aversões alimentares", type: "textarea", max_score: 0.5 },
      { id: uid("nn",10), label: "Consumo hídrico diário", type: "text", max_score: 0.5 },
      { id: uid("nn",11), label: "Sintomas Gastrointestinais", type: "section_header" },
      { id: uid("nn",12), label: "Sintomas GI (náusea, vômito, diarreia, constipação)", type: "checkbox", options: ["Náusea","Vômito","Diarreia","Constipação","Distensão","Pirose","Nenhum"], max_score: 1 },
      { id: uid("nn",13), label: "Hábito intestinal", type: "text", max_score: 0.5 },
      { id: uid("nn",14), label: "Antecedentes", type: "section_header" },
      { id: uid("nn",15), label: "Doenças crônicas e uso de medicamentos", type: "textarea", max_score: 1 },
      { id: uid("nn",16), label: "Atividade física (tipo, frequência, duração)", type: "textarea", max_score: 0.5 },
      { id: uid("nn",17), label: "Suplementos em uso", type: "textarea", max_score: 0.5 },
      { id: uid("nn",18), label: "Observações gerais", type: "textarea", max_score: 0.5 },
    ],
  },
  {
    area: "nutrition", module_type: "anamnese_nutricional", form_type: "answer_key",
    title: "Espelho — Anamnese Nutricional",
    description: "Gabarito de anamnese nutricional",
    content_json: [
      { id: uid("nne",0), label: "Dados Pessoais", type: "section_header" },
      { id: uid("nne",1), label: "Nome completo", type: "text" },
      { id: uid("nne",2), label: "Idade", type: "text" },
      { id: uid("nne",3), label: "Sexo", type: "radio", options: ["Masculino","Feminino","Outro"] },
      { id: uid("nne",5), label: "História Alimentar", type: "section_header" },
      { id: uid("nne",6), label: "Recordatório 24h", type: "textarea", max_score: 2, correct_answer: "Detalhar todas as refeições com horários, alimentos, quantidades e modo de preparo." },
      { id: uid("nne",7), label: "Frequência alimentar", type: "textarea", max_score: 1.5, correct_answer: "Avaliar frequência semanal de cada grupo alimentar." },
      { id: uid("nne",8), label: "Restrições/Alergias", type: "textarea", max_score: 0.5, correct_answer: "Alergias alimentares, intolerâncias e restrições dietéticas." },
      { id: uid("nne",11), label: "Sintomas GI", type: "section_header" },
      { id: uid("nne",12), label: "Sintomas GI", type: "checkbox", options: ["Náusea","Vômito","Diarreia","Constipação","Distensão","Pirose","Nenhum"], max_score: 1 },
      { id: uid("nne",14), label: "Antecedentes", type: "section_header" },
      { id: uid("nne",15), label: "Doenças e medicamentos", type: "textarea", max_score: 1, correct_answer: "Registrar comorbidades e medicamentos que afetam estado nutricional." },
      { id: uid("nne",18), label: "Observações", type: "textarea", max_score: 0.5, correct_answer: "Aspectos socioeconômicos e culturais que influenciam alimentação." },
    ],
  },
  // ── Avaliação Antropométrica ──
  {
    area: "nutrition", module_type: "avaliacao_antropometrica", form_type: "standard",
    title: "Ficha de Avaliação Antropométrica",
    description: "Medidas corporais e classificação nutricional",
    content_json: [
      { id: uid("at",0), label: "Medidas Básicas", type: "section_header" },
      { id: uid("at",1), label: "Peso atual (kg)", type: "text", required: true, max_score: 0.5 },
      { id: uid("at",2), label: "Altura (cm)", type: "text", required: true, max_score: 0.5 },
      { id: uid("at",3), label: "IMC calculado (kg/m²)", type: "text", required: true, max_score: 1 },
      { id: uid("at",4), label: "Classificação do IMC", type: "radio", options: ["Desnutrição","Eutrofia","Sobrepeso","Obesidade grau I","Obesidade grau II","Obesidade grau III"], required: true, max_score: 1 },
      { id: uid("at",5), label: "Circunferências", type: "section_header" },
      { id: uid("at",6), label: "Circunferência da cintura (cm)", type: "text", max_score: 0.5 },
      { id: uid("at",7), label: "Circunferência do quadril (cm)", type: "text", max_score: 0.5 },
      { id: uid("at",8), label: "Relação cintura/quadril", type: "text", max_score: 0.5 },
      { id: uid("at",9), label: "Circunferência do braço (cm)", type: "text", max_score: 0.5 },
      { id: uid("at",10), label: "Dobras Cutâneas", type: "section_header" },
      { id: uid("at",11), label: "Tricipital (mm)", type: "text", max_score: 0.5 },
      { id: uid("at",12), label: "Subescapular (mm)", type: "text", max_score: 0.5 },
      { id: uid("at",13), label: "Supra-ilíaca (mm)", type: "text", max_score: 0.5 },
      { id: uid("at",14), label: "% Gordura corporal estimado", type: "text", max_score: 1 },
      { id: uid("at",15), label: "Classificação Nutricional", type: "section_header" },
      { id: uid("at",16), label: "Diagnóstico nutricional", type: "textarea", required: true, max_score: 2 },
    ],
  },
  {
    area: "nutrition", module_type: "avaliacao_antropometrica", form_type: "answer_key",
    title: "Espelho — Avaliação Antropométrica",
    description: "Gabarito de antropometria",
    content_json: [
      { id: uid("ate",0), label: "Medidas Básicas", type: "section_header" },
      { id: uid("ate",1), label: "Peso atual (kg)", type: "text", max_score: 0.5, correct_answer: "Aferição com balança calibrada, paciente com roupas leves." },
      { id: uid("ate",2), label: "Altura (cm)", type: "text", max_score: 0.5, correct_answer: "Estadiômetro, posição de Frankfurt." },
      { id: uid("ate",3), label: "IMC", type: "text", max_score: 1, correct_answer: "Calcular corretamente: Peso / Altura²." },
      { id: uid("ate",4), label: "Classificação IMC", type: "radio", options: ["Desnutrição","Eutrofia","Sobrepeso","Obesidade grau I","Obesidade grau II","Obesidade grau III"], max_score: 1 },
      { id: uid("ate",15), label: "Classificação Nutricional", type: "section_header" },
      { id: uid("ate",16), label: "Diagnóstico nutricional", type: "textarea", max_score: 2, correct_answer: "Integrar IMC, composição corporal e distribuição de gordura para diagnóstico." },
    ],
  },
  // ── Plano Alimentar ──
  {
    area: "nutrition", module_type: "plano_alimentar", form_type: "standard",
    title: "Plano Alimentar",
    description: "Prescrição dietética individualizada",
    content_json: [
      { id: uid("pa",0), label: "Cálculo Energético", type: "section_header" },
      { id: uid("pa",1), label: "VET calculado (kcal/dia)", type: "text", required: true, max_score: 2 },
      { id: uid("pa",2), label: "Fórmula utilizada", type: "radio", options: ["Harris-Benedict","Mifflin-St Jeor","DRI","Outra"], max_score: 0.5 },
      { id: uid("pa",3), label: "Distribuição de Macronutrientes", type: "section_header" },
      { id: uid("pa",4), label: "Carboidratos (% e g/dia)", type: "text", required: true, max_score: 1 },
      { id: uid("pa",5), label: "Proteínas (% e g/dia)", type: "text", required: true, max_score: 1 },
      { id: uid("pa",6), label: "Lipídios (% e g/dia)", type: "text", required: true, max_score: 1 },
      { id: uid("pa",7), label: "Prescrição por Refeição", type: "section_header" },
      { id: uid("pa",8), label: "Café da manhã", type: "textarea", required: true, max_score: 0.5 },
      { id: uid("pa",9), label: "Lanche da manhã", type: "textarea", max_score: 0.5 },
      { id: uid("pa",10), label: "Almoço", type: "textarea", required: true, max_score: 0.5 },
      { id: uid("pa",11), label: "Lanche da tarde", type: "textarea", max_score: 0.5 },
      { id: uid("pa",12), label: "Jantar", type: "textarea", required: true, max_score: 0.5 },
      { id: uid("pa",13), label: "Ceia", type: "textarea", max_score: 0.5 },
      { id: uid("pa",14), label: "Orientações Específicas", type: "section_header" },
      { id: uid("pa",15), label: "Orientações nutricionais específicas para a condição", type: "textarea", required: true, max_score: 1.5 },
    ],
  },
  {
    area: "nutrition", module_type: "plano_alimentar", form_type: "answer_key",
    title: "Espelho — Plano Alimentar",
    description: "Gabarito de plano alimentar",
    content_json: [
      { id: uid("pae",0), label: "Cálculo Energético", type: "section_header" },
      { id: uid("pae",1), label: "VET", type: "text", max_score: 2, correct_answer: "Cálculo correto do VET com fator atividade e fator injúria quando aplicável." },
      { id: uid("pae",3), label: "Macronutrientes", type: "section_header" },
      { id: uid("pae",4), label: "Carboidratos", type: "text", max_score: 1, correct_answer: "45-65% do VET conforme DRI, ajustado à condição clínica." },
      { id: uid("pae",5), label: "Proteínas", type: "text", max_score: 1, correct_answer: "10-35% do VET ou g/kg/dia conforme condição." },
      { id: uid("pae",6), label: "Lipídios", type: "text", max_score: 1, correct_answer: "20-35% do VET com perfil de ácidos graxos adequado." },
      { id: uid("pae",14), label: "Orientações", type: "section_header" },
      { id: uid("pae",15), label: "Orientações específicas", type: "textarea", max_score: 1.5, correct_answer: "Orientações baseadas em diretrizes para a condição clínica do paciente." },
    ],
  },
  // ── Orientação Nutricional ──
  {
    area: "nutrition", module_type: "orientacao_nutricional", form_type: "standard",
    title: "Ficha de Orientação Nutricional",
    description: "Educação alimentar e nutricional",
    content_json: [
      { id: uid("on",0), label: "Metas Nutricionais", type: "section_header" },
      { id: uid("on",1), label: "Meta principal do tratamento", type: "textarea", required: true, max_score: 2 },
      { id: uid("on",2), label: "Metas secundárias", type: "textarea", max_score: 1 },
      { id: uid("on",3), label: "Orientações por Patologia", type: "section_header" },
      { id: uid("on",4), label: "Orientações específicas para a condição clínica", type: "textarea", required: true, max_score: 3 },
      { id: uid("on",5), label: "Alimentos recomendados", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("on",6), label: "Alimentos a evitar/restringir", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("on",7), label: "Material Educativo", type: "section_header" },
      { id: uid("on",8), label: "Materiais educativos entregues/indicados", type: "textarea", max_score: 1 },
    ],
  },
  {
    area: "nutrition", module_type: "orientacao_nutricional", form_type: "answer_key",
    title: "Espelho — Orientação Nutricional",
    description: "Gabarito de orientação nutricional",
    content_json: [
      { id: uid("one",0), label: "Metas Nutricionais", type: "section_header" },
      { id: uid("one",1), label: "Meta principal", type: "textarea", max_score: 2, correct_answer: "Meta SMART: específica, mensurável, atingível, relevante e temporal." },
      { id: uid("one",3), label: "Orientações por Patologia", type: "section_header" },
      { id: uid("one",4), label: "Orientações específicas", type: "textarea", max_score: 3, correct_answer: "Orientações baseadas em consensos e diretrizes atualizadas." },
      { id: uid("one",5), label: "Alimentos recomendados", type: "textarea", max_score: 1.5, correct_answer: "Lista de alimentos funcionais e protetores para a condição." },
      { id: uid("one",6), label: "Alimentos a evitar", type: "textarea", max_score: 1.5, correct_answer: "Justificar restrições com base em mecanismos fisiopatológicos." },
    ],
  },
];
