import type { FormField } from "@/components/forms/types";

const uid = (prefix: string, i: number) => `${prefix}-${i}`;

export const pharmacyTemplates: { area: string; module_type: string; form_type: string; title: string; description: string; content_json: FormField[] }[] = [
  // ── Anamnese ──
  {
    area: "pharmacy", module_type: "anamnese", form_type: "standard",
    title: "Ficha de Anamnese Farmacêutica",
    description: "Coleta de dados do paciente com foco farmacoterapêutico",
    content_json: [
      { id: uid("an",0), label: "Dados do Paciente", type: "section_header" },
      { id: uid("an",1), label: "Nome completo", type: "text", required: true },
      { id: uid("an",2), label: "Idade", type: "text", required: true },
      { id: uid("an",3), label: "Sexo", type: "radio", options: ["Masculino","Feminino","Outro"], required: true },
      { id: uid("an",4), label: "Queixa Principal", type: "section_header" },
      { id: uid("an",5), label: "Qual a queixa principal do paciente?", type: "textarea", required: true, max_score: 1 },
      { id: uid("an",6), label: "História da Moléstia Atual (HMA)", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("an",7), label: "Farmacoterapia", type: "section_header" },
      { id: uid("an",8), label: "Medicamentos em uso (nome, dose, posologia, via)", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("an",9), label: "Uso de medicamentos sem prescrição (OTC)?", type: "radio", options: ["Sim","Não"], required: true, max_score: 0.5 },
      { id: uid("an",10), label: "Alergias conhecidas a medicamentos", type: "textarea", max_score: 0.5 },
      { id: uid("an",11), label: "Reações adversas prévias", type: "textarea", max_score: 0.5 },
      { id: uid("an",12), label: "Hábitos e Antecedentes", type: "section_header" },
      { id: uid("an",13), label: "Hábitos de vida (tabagismo, etilismo, atividade física)", type: "textarea", max_score: 0.5 },
      { id: uid("an",14), label: "Antecedentes patológicos", type: "textarea", max_score: 0.5 },
      { id: uid("an",15), label: "Exame Físico Dirigido", type: "section_header" },
      { id: uid("an",16), label: "PA (mmHg)", type: "text", max_score: 0.5 },
      { id: uid("an",17), label: "FC (bpm)", type: "text", max_score: 0.5 },
      { id: uid("an",18), label: "Glicemia capilar (mg/dL)", type: "text", max_score: 0.5 },
      { id: uid("an",19), label: "Observações adicionais", type: "textarea", max_score: 0.5 },
    ],
  },
  {
    area: "pharmacy", module_type: "anamnese", form_type: "answer_key",
    title: "Espelho — Anamnese Farmacêutica",
    description: "Gabarito com critérios de pontuação para anamnese",
    content_json: [
      { id: uid("ane",0), label: "Dados do Paciente", type: "section_header" },
      { id: uid("ane",1), label: "Nome completo", type: "text" },
      { id: uid("ane",2), label: "Idade", type: "text" },
      { id: uid("ane",3), label: "Sexo", type: "radio", options: ["Masculino","Feminino","Outro"] },
      { id: uid("ane",4), label: "Queixa Principal", type: "section_header" },
      { id: uid("ane",5), label: "Qual a queixa principal do paciente?", type: "textarea", max_score: 1, correct_answer: "Descrever a queixa principal com clareza, incluindo início, localização, intensidade e fatores associados." },
      { id: uid("ane",6), label: "História da Moléstia Atual (HMA)", type: "textarea", max_score: 1.5, correct_answer: "Cronologia dos sintomas, fatores de melhora/piora, tratamentos já tentados e evolução." },
      { id: uid("ane",7), label: "Farmacoterapia", type: "section_header" },
      { id: uid("ane",8), label: "Medicamentos em uso (nome, dose, posologia, via)", type: "textarea", max_score: 1.5, correct_answer: "Listar todos os medicamentos com nome genérico/comercial, dose, frequência e via de administração." },
      { id: uid("ane",9), label: "Uso de medicamentos sem prescrição (OTC)?", type: "radio", options: ["Sim","Não"], max_score: 0.5, correct_answer: 0 },
      { id: uid("ane",10), label: "Alergias conhecidas a medicamentos", type: "textarea", max_score: 0.5, correct_answer: "Registrar todas as alergias medicamentosas e tipo de reação." },
      { id: uid("ane",11), label: "Reações adversas prévias", type: "textarea", max_score: 0.5, correct_answer: "Descrever RAMs prévias com medicamento causador e manifestação." },
      { id: uid("ane",12), label: "Hábitos e Antecedentes", type: "section_header" },
      { id: uid("ane",13), label: "Hábitos de vida", type: "textarea", max_score: 0.5, correct_answer: "Investigar tabagismo, etilismo, uso de drogas, alimentação e exercício." },
      { id: uid("ane",14), label: "Antecedentes patológicos", type: "textarea", max_score: 0.5, correct_answer: "Doenças crônicas, cirurgias, internações e histórico familiar relevante." },
      { id: uid("ane",15), label: "Exame Físico Dirigido", type: "section_header" },
      { id: uid("ane",16), label: "PA (mmHg)", type: "text", max_score: 0.5, correct_answer: "Aferir corretamente e registrar valores sistólico/diastólico." },
      { id: uid("ane",17), label: "FC (bpm)", type: "text", max_score: 0.5, correct_answer: "Verificar ritmo e frequência." },
      { id: uid("ane",18), label: "Glicemia capilar (mg/dL)", type: "text", max_score: 0.5, correct_answer: "Registrar valor e condição (jejum/pós-prandial)." },
      { id: uid("ane",19), label: "Observações adicionais", type: "textarea", max_score: 0.5, correct_answer: "Achados relevantes do exame físico dirigido." },
    ],
  },
  // ── SOAP ──
  {
    area: "pharmacy", module_type: "soap", form_type: "standard",
    title: "Nota SOAP Farmacêutica",
    description: "Registro estruturado do atendimento farmacêutico",
    content_json: [
      { id: uid("sp",0), label: "S — Subjetivo", type: "section_header" },
      { id: uid("sp",1), label: "Relato do paciente (queixas, sintomas, preocupações)", type: "textarea", required: true, max_score: 2 },
      { id: uid("sp",2), label: "Adesão ao tratamento atual", type: "radio", options: ["Boa","Regular","Ruim"], max_score: 0.5 },
      { id: uid("sp",3), label: "O — Objetivo", type: "section_header" },
      { id: uid("sp",4), label: "Dados objetivos (sinais vitais, exames laboratoriais)", type: "textarea", required: true, max_score: 2 },
      { id: uid("sp",5), label: "A — Avaliação", type: "section_header" },
      { id: uid("sp",6), label: "Problemas relacionados a medicamentos identificados", type: "textarea", required: true, max_score: 2.5 },
      { id: uid("sp",7), label: "Classificação do PRM", type: "checkbox", options: ["Indicação sem tratamento","Tratamento sem indicação","Dose subterapêutica","Dose supraterapêutica","Reação adversa","Interação medicamentosa","Não adesão"], max_score: 1 },
      { id: uid("sp",8), label: "P — Plano", type: "section_header" },
      { id: uid("sp",9), label: "Intervenções farmacêuticas propostas", type: "textarea", required: true, max_score: 2 },
    ],
  },
  {
    area: "pharmacy", module_type: "soap", form_type: "answer_key",
    title: "Espelho — Nota SOAP",
    description: "Gabarito SOAP farmacêutico",
    content_json: [
      { id: uid("spe",0), label: "S — Subjetivo", type: "section_header" },
      { id: uid("spe",1), label: "Relato do paciente", type: "textarea", max_score: 2, correct_answer: "Incluir queixa principal, sintomas associados, tempo de evolução e impacto na qualidade de vida." },
      { id: uid("spe",2), label: "Adesão ao tratamento", type: "radio", options: ["Boa","Regular","Ruim"], max_score: 0.5 },
      { id: uid("spe",3), label: "O — Objetivo", type: "section_header" },
      { id: uid("spe",4), label: "Dados objetivos", type: "textarea", max_score: 2, correct_answer: "Registrar PA, FC, T, exames laboratoriais recentes e valores de referência." },
      { id: uid("spe",5), label: "A — Avaliação", type: "section_header" },
      { id: uid("spe",6), label: "PRMs identificados", type: "textarea", max_score: 2.5, correct_answer: "Identificar e classificar todos os PRMs conforme o Método Dáder ou Cipolle." },
      { id: uid("spe",7), label: "Classificação do PRM", type: "checkbox", options: ["Indicação sem tratamento","Tratamento sem indicação","Dose subterapêutica","Dose supraterapêutica","Reação adversa","Interação medicamentosa","Não adesão"], max_score: 1 },
      { id: uid("spe",8), label: "P — Plano", type: "section_header" },
      { id: uid("spe",9), label: "Intervenções propostas", type: "textarea", max_score: 2, correct_answer: "Propor intervenções claras: ajuste de dose, substituição, educação do paciente, encaminhamento." },
    ],
  },
  // ── Reconciliação ──
  {
    area: "pharmacy", module_type: "reconciliacao", form_type: "standard",
    title: "Ficha de Reconciliação Medicamentosa",
    description: "Comparação entre medicamentos prescritos e em uso",
    content_json: [
      { id: uid("rc",0), label: "Identificação", type: "section_header" },
      { id: uid("rc",1), label: "Nome do paciente", type: "text", required: true },
      { id: uid("rc",2), label: "Transição de cuidado", type: "radio", options: ["Admissão","Transferência","Alta"], required: true, max_score: 0.5 },
      { id: uid("rc",3), label: "Medicamentos", type: "section_header" },
      { id: uid("rc",4), label: "Lista de medicamentos em uso domiciliar", type: "textarea", required: true, max_score: 2 },
      { id: uid("rc",5), label: "Lista de medicamentos prescritos na instituição", type: "textarea", required: true, max_score: 2 },
      { id: uid("rc",6), label: "Discrepâncias", type: "section_header" },
      { id: uid("rc",7), label: "Discrepâncias identificadas", type: "textarea", required: true, max_score: 2.5 },
      { id: uid("rc",8), label: "Tipo de discrepância", type: "checkbox", options: ["Omissão","Comissão","Dose diferente","Frequência diferente","Via diferente","Duplicidade"], max_score: 1 },
      { id: uid("rc",9), label: "Intervenções", type: "section_header" },
      { id: uid("rc",10), label: "Intervenções propostas e justificativa", type: "textarea", required: true, max_score: 2 },
    ],
  },
  {
    area: "pharmacy", module_type: "reconciliacao", form_type: "answer_key",
    title: "Espelho — Reconciliação Medicamentosa",
    description: "Gabarito de reconciliação",
    content_json: [
      { id: uid("rce",0), label: "Identificação", type: "section_header" },
      { id: uid("rce",1), label: "Nome do paciente", type: "text" },
      { id: uid("rce",2), label: "Transição de cuidado", type: "radio", options: ["Admissão","Transferência","Alta"], max_score: 0.5 },
      { id: uid("rce",3), label: "Medicamentos", type: "section_header" },
      { id: uid("rce",4), label: "Medicamentos domiciliares", type: "textarea", max_score: 2, correct_answer: "Listar todos os medicamentos com dose, frequência e via. Incluir fitoterápicos e suplementos." },
      { id: uid("rce",5), label: "Medicamentos institucionais", type: "textarea", max_score: 2, correct_answer: "Listar prescrição completa com dose, frequência, via e horários." },
      { id: uid("rce",6), label: "Discrepâncias", type: "section_header" },
      { id: uid("rce",7), label: "Discrepâncias identificadas", type: "textarea", max_score: 2.5, correct_answer: "Identificar todas as discrepâncias comparando as duas listas medicamento a medicamento." },
      { id: uid("rce",8), label: "Tipo de discrepância", type: "checkbox", options: ["Omissão","Comissão","Dose diferente","Frequência diferente","Via diferente","Duplicidade"], max_score: 1 },
      { id: uid("rce",9), label: "Intervenções", type: "section_header" },
      { id: uid("rce",10), label: "Intervenções e justificativa", type: "textarea", max_score: 2, correct_answer: "Propor resolução para cada discrepância com base em evidências e diretrizes." },
    ],
  },
  // ── Documentação ──
  {
    area: "pharmacy", module_type: "documentacao", form_type: "standard",
    title: "Quadro Resumo e Encaminhamento",
    description: "Documentação final do atendimento farmacêutico",
    content_json: [
      { id: uid("dc",0), label: "Ficha de Encaminhamento", type: "section_header" },
      { id: uid("dc",1), label: "Motivo do encaminhamento", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("dc",2), label: "Profissional/serviço de destino", type: "text", required: true, max_score: 0.5 },
      { id: uid("dc",3), label: "Resumo do caso para o profissional", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("dc",4), label: "Quadro Resumo de Medicamentos", type: "section_header" },
      { id: uid("dc",5), label: "Medicamento 1 — Nome, dose, posologia, observações", type: "textarea", max_score: 0.5 },
      { id: uid("dc",6), label: "Medicamento 2 — Nome, dose, posologia, observações", type: "textarea", max_score: 0.5 },
      { id: uid("dc",7), label: "Medicamento 3 — Nome, dose, posologia, observações", type: "textarea", max_score: 0.5 },
      { id: uid("dc",8), label: "Orientações ao paciente", type: "textarea", required: true, max_score: 1.5 },
      { id: uid("dc",9), label: "Seguimento proposto", type: "textarea", max_score: 1 },
    ],
  },
  {
    area: "pharmacy", module_type: "documentacao", form_type: "answer_key",
    title: "Espelho — Quadro Resumo",
    description: "Gabarito de documentação farmacêutica",
    content_json: [
      { id: uid("dce",0), label: "Ficha de Encaminhamento", type: "section_header" },
      { id: uid("dce",1), label: "Motivo do encaminhamento", type: "textarea", max_score: 1.5, correct_answer: "Justificar clinicamente o encaminhamento com base nos achados da avaliação." },
      { id: uid("dce",2), label: "Profissional/serviço de destino", type: "text", max_score: 0.5, correct_answer: "Indicar especialidade adequada ao problema identificado." },
      { id: uid("dce",3), label: "Resumo do caso", type: "textarea", max_score: 1.5, correct_answer: "Síntese objetiva: diagnóstico, medicamentos, PRMs e intervenções realizadas." },
      { id: uid("dce",4), label: "Quadro Resumo de Medicamentos", type: "section_header" },
      { id: uid("dce",5), label: "Medicamento 1", type: "textarea", max_score: 0.5, correct_answer: "Nome genérico, dose, frequência, via e observações relevantes." },
      { id: uid("dce",6), label: "Medicamento 2", type: "textarea", max_score: 0.5, correct_answer: "Nome genérico, dose, frequência, via e observações relevantes." },
      { id: uid("dce",7), label: "Medicamento 3", type: "textarea", max_score: 0.5, correct_answer: "Nome genérico, dose, frequência, via e observações relevantes." },
      { id: uid("dce",8), label: "Orientações ao paciente", type: "textarea", max_score: 1.5, correct_answer: "Orientações claras sobre uso de medicamentos, efeitos adversos e sinais de alerta." },
      { id: uid("dce",9), label: "Seguimento proposto", type: "textarea", max_score: 1, correct_answer: "Definir prazo de retorno, exames de acompanhamento e metas terapêuticas." },
    ],
  },
];
